CREATE TABLE [dbo].[AREA_PROFESSOR] (
    [COD_PROFESSOR] SMALLINT NOT NULL,
    [COD_AREA]      TINYINT  NOT NULL,
    PRIMARY KEY CLUSTERED ([COD_PROFESSOR] ASC, [COD_AREA] ASC),
    CONSTRAINT [FK_AREA_AREA_PROFESSOR] FOREIGN KEY ([COD_AREA]) REFERENCES [dbo].[AREA] ([CODIGO]),
    CONSTRAINT [FK_PROFESSOR_AREA_PROFESSOR] FOREIGN KEY ([COD_PROFESSOR]) REFERENCES [dbo].[PROFESSOR] ([CODIGO])
);

