CREATE TABLE [dbo].[AREA_DISCIPLINA] (
    [COD_AREA]       TINYINT NOT NULL,
    [COD_DISCIPLINA] TINYINT NOT NULL,
    CONSTRAINT [FK_AREA_AREA_DISCIPLINA] FOREIGN KEY ([COD_AREA]) REFERENCES [dbo].[AREA] ([CODIGO]),
    CONSTRAINT [FK_DISCIPLINA_AREA_DISCIPLINA] FOREIGN KEY ([COD_DISCIPLINA]) REFERENCES [dbo].[DISCIPLINA] ([CODIGO])
);

