CREATE TABLE [dbo].[ATENDIMENTO_ALUNO] (
    [CODIGO]                    INT          IDENTITY (1, 1) NOT NULL,
    [COD_DISCIPLINA_ALUNO]      INT          NOT NULL,
    [COD_ATENDIMENTO]           SMALLINT     NOT NULL,
    [COD_PROFESSOR]             SMALLINT     NOT NULL,
    [DT_ATENDIMENTO]            DATETIME     NOT NULL,
    [COD_PROFESSOR_MODIFICACAO] SMALLINT     NULL,
    [DT_MODIFICACAO]            DATETIME     NULL,
    [MODULO]                    VARCHAR (20) NULL,
    [ORDEM]                     TINYINT      NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_ATENDIMENTO_ATENDIMENTO_ALUNO] FOREIGN KEY ([COD_ATENDIMENTO]) REFERENCES [dbo].[ATENDIMENTO] ([CODIGO]),
    CONSTRAINT [FK_DISCIPLINA_ALUNO_ATENDIMENTO_ALUNO] FOREIGN KEY ([COD_DISCIPLINA_ALUNO]) REFERENCES [dbo].[DISCIPLINA_ALUNO] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_ATENDIMENTO_ALUNO] FOREIGN KEY ([COD_PROFESSOR]) REFERENCES [dbo].[PROFESSOR] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_MODIFICACAO_ATENDIMENTO_ALUNO] FOREIGN KEY ([COD_PROFESSOR_MODIFICACAO]) REFERENCES [dbo].[PROFESSOR] ([CODIGO])
);

