CREATE TABLE [dbo].[ATENDIMENTO] (
    [CODIGO]         SMALLINT     IDENTITY (1, 1) NOT NULL,
    [NOME]           VARCHAR (50) NOT NULL,
    [COD_DISCIPLINA] TINYINT      NOT NULL,
    [MENCAO]         BIT          NOT NULL,
    [ATIVO]          BIT          NOT NULL,
    [ORDEM]          TINYINT      NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_DISCIPLINA_ATENDIMENTO] FOREIGN KEY ([COD_DISCIPLINA]) REFERENCES [dbo].[DISCIPLINA] ([CODIGO])
);

