CREATE TABLE [dbo].[CARTAO_ACESSO] (
    [CODIGO]    INT IDENTITY (1, 1) NOT NULL,
    [ALUNO]     INT NULL,
    [PROFESSOR] INT NULL,
    [ESTADO]    BIT NOT NULL,
    [IMPRESSO]  BIT NOT NULL, 
    [N_MAT] VARCHAR(50) NULL
);

