CREATE TABLE [dbo].[CIDADE] (
    [CODIGO] SMALLINT      IDENTITY (1, 1) NOT NULL,
    [NOME]   VARCHAR (MAX) NOT NULL,
    [COD_UF] SMALLINT      NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_UF_CIDADE] FOREIGN KEY ([COD_UF]) REFERENCES [dbo].[UF] ([CODIGO])
);

