CREATE TABLE [dbo].[DEFICIENCIA_ALUNO] (
    [N_MAT]           INT           NOT NULL,
    [COD_DEFICIENCIA] SMALLINT      NOT NULL,
    [OBS]             VARCHAR (MAX) NULL,
    CONSTRAINT [FK_ALUNO_DEFICIENCIA_ALUNO] FOREIGN KEY ([N_MAT]) REFERENCES [dbo].[ALUNO] ([N_MAT]),
    CONSTRAINT [FK_DEFICIENCIA_DEFICIENCIA_ALUNO] FOREIGN KEY ([COD_DEFICIENCIA]) REFERENCES [dbo].[DEFICIENCIA] ([CODIGO])
);

