CREATE TABLE [dbo].[DEFICIENCIA_USUARIO] (
    [COD_USUARIO]     SMALLINT      NOT NULL,
    [COD_DEFICIENCIA] SMALLINT      NOT NULL,
    [OBS]             VARCHAR (MAX) NULL,
    CONSTRAINT [FK_DEFICIENCIA_DEFICIENCIA_USUARIO] FOREIGN KEY ([COD_DEFICIENCIA]) REFERENCES [dbo].[DEFICIENCIA] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_DEFICIENCIA_USUARIO] FOREIGN KEY ([COD_USUARIO]) REFERENCES [dbo].[USUARIO] ([CODIGO])
);

