CREATE TABLE [dbo].[DEFICIENCIA] (
    [CODIGO]           SMALLINT     NOT NULL,
    [NOME]             VARCHAR (50) NOT NULL,
    [TIPO_DEFICIENCIA] TINYINT      NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC)
);

