CREATE TABLE [dbo].[DISCIPLINA_ALUNO] (
    [CODIGO]           INT     IDENTITY (1, 1) NOT NULL,
    [COD_ENSINO_ALUNO] INT     NULL,
    [COD_DISCIPLINA]   TINYINT NULL,
    [ATUAL]            BIT     NULL,
    [CONCLUIDA]        BIT     NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_DISCIPLINA_DISCIPLINA_ALUNO] FOREIGN KEY ([COD_DISCIPLINA]) REFERENCES [dbo].[DISCIPLINA] ([CODIGO]),
    CONSTRAINT [FK_ENSINO_ALUNO] FOREIGN KEY ([COD_ENSINO_ALUNO]) REFERENCES [dbo].[ENSINO_ALUNO] ([CODIGO])
);

