CREATE TABLE [dbo].[EMPREGO_ALUNO] (
    [N_MAT]        INT           NOT NULL,
    [NOME_EMPRESA] VARCHAR (MAX) NULL,
    [TELEFONE]     VARCHAR (MAX) NULL,
    [COD_CIDADE]   SMALLINT      NULL,
    PRIMARY KEY CLUSTERED ([N_MAT] ASC),
    CONSTRAINT [FK_ALUNO_LOCAL_NASCIMENTO] FOREIGN KEY ([N_MAT]) REFERENCES [dbo].[ALUNO] ([N_MAT]),
    CONSTRAINT [FK_CIDADE_LOCAL_NASCIMENTO] FOREIGN KEY ([COD_CIDADE]) REFERENCES [dbo].[CIDADE] ([CODIGO])
);

