CREATE TABLE [dbo].[ENDERECO_ALUNO] (
    [N_MAT]       INT           NOT NULL,
    [COD_CIDADE]  SMALLINT      NOT NULL,
    [CEP]         VARCHAR (MAX) NULL,
    [LOGRADOURO]  VARCHAR (MAX) NULL,
    [NUMERO]      INT           NULL,
    [BAIRRO]      VARCHAR (MAX) NULL,
    [COMPLEMENTO] VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([N_MAT] ASC),
    CONSTRAINT [FK_ALUNO_ENDERECO] FOREIGN KEY ([N_MAT]) REFERENCES [dbo].[ALUNO] ([N_MAT]),
    CONSTRAINT [FK_CIDADE_ENDERECO] FOREIGN KEY ([COD_CIDADE]) REFERENCES [dbo].[CIDADE] ([CODIGO])
);

