CREATE TABLE [dbo].[ENSINO_ALUNO] (
    [CODIGO]     INT      IDENTITY (1, 1) NOT NULL,
    [N_MAT]      INT      NULL,
    [COD_ENSINO] TINYINT  NULL,
    [ATUAL]      BIT      NULL,
    [DT_INICIO]  DATETIME NULL,
    [DT_TERMINO] DATETIME NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_ALUNO_ENSINO_ALUNO] FOREIGN KEY ([N_MAT]) REFERENCES [dbo].[ALUNO] ([N_MAT])
);

