CREATE TABLE [dbo].[LOCAL_NASCIMENTO] (
    [N_MAT]      INT      NOT NULL,
    [COD_CIDADE] SMALLINT NULL,
    PRIMARY KEY CLUSTERED ([N_MAT] ASC),
    CONSTRAINT [FK_ALUNO_LOCAL_NASCIMENTO_ALUNO] FOREIGN KEY ([N_MAT]) REFERENCES [dbo].[ALUNO] ([N_MAT]),
    CONSTRAINT [FK_CIDADE_LOCAL_NASCIMENTO_ALUNO] FOREIGN KEY ([COD_CIDADE]) REFERENCES [dbo].[CIDADE] ([CODIGO])
);

