CREATE TABLE [dbo].[LOG_ACESSO] (
    [CODIGO]           INT      NOT NULL,
    [COD_USUARIO]      SMALLINT NOT NULL,
    [TIPO]             BIT      NOT NULL,
    [DATA_HORA_ACESSO] DATETIME NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_USUARIO_LOG_ACESSO] FOREIGN KEY ([COD_USUARIO]) REFERENCES [dbo].[USUARIO] ([CODIGO])
);

