CREATE TABLE [dbo].[MEDIA] (
    [COD_DISCIPLINA_ALUNO]    INT           NOT NULL,
    [VALOR]                   VARCHAR (20)  NOT NULL,
    [DT_MEDIA]                DATE          NOT NULL,
    [COD_USUARIO]             SMALLINT      NOT NULL,
    [COD_USUARIO_MODIFICACAO] SMALLINT      NULL,
    [DT_MODIFICACAO]          DATETIME      NULL,
    [COD_ATENDIMENTO_ALUNO]   INT           NULL,
    [COD_CIDADE]              INT           NULL,
    [INSTITUICAO]             VARCHAR (MAX) NULL,
    CONSTRAINT [FK_ATENDIMENTO_ALUNO_MEDIA] FOREIGN KEY ([COD_ATENDIMENTO_ALUNO]) REFERENCES [dbo].[ATENDIMENTO_ALUNO] ([CODIGO]),
    CONSTRAINT [FK_DISCIPLINA_ALUNO_MEDIA] FOREIGN KEY ([COD_DISCIPLINA_ALUNO]) REFERENCES [dbo].[DISCIPLINA_ALUNO] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_MEDIA] FOREIGN KEY ([COD_USUARIO]) REFERENCES [dbo].[USUARIO] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_MODIFICACAO_MEDIA] FOREIGN KEY ([COD_USUARIO_MODIFICACAO]) REFERENCES [dbo].[USUARIO] ([CODIGO])
);

