CREATE TABLE [dbo].[PROFESSOR] (
    [CODIGO]         SMALLINT NOT NULL,
    [COD_DISCIPLINA] TINYINT  NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_DISCIPLINA_PROFESSOR] FOREIGN KEY ([COD_DISCIPLINA]) REFERENCES [dbo].[DISCIPLINA] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_PROFESSOR] FOREIGN KEY ([CODIGO]) REFERENCES [dbo].[USUARIO] ([CODIGO])
);

