CREATE TABLE [dbo].[REMATRICULA] (
    [CODIGO]           INT      IDENTITY (1, 1) NOT NULL,
    [DT_REMATRICULA]   DATETIME NOT NULL,
    [COD_USUARIO]      SMALLINT NOT NULL,
    [COD_ENSINO_ALUNO] INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_ENSINO_ALUNO_REMATRICULA] FOREIGN KEY ([COD_ENSINO_ALUNO]) REFERENCES [dbo].[ENSINO_ALUNO] ([CODIGO]),
    CONSTRAINT [FK_USUARIO_REMATRICULA] FOREIGN KEY ([COD_USUARIO]) REFERENCES [dbo].[USUARIO] ([CODIGO])
);

