CREATE TABLE [dbo].[UF] (
    [CODIGO]   SMALLINT      IDENTITY (1, 1) NOT NULL,
    [NOME]     VARCHAR (MAX) NOT NULL,
    [SIGLA]    VARCHAR (2)   NULL,
    [COD_PAIS] TINYINT       NOT NULL,
    PRIMARY KEY CLUSTERED ([CODIGO] ASC),
    CONSTRAINT [FK_PAIS_UF] FOREIGN KEY ([COD_PAIS]) REFERENCES [dbo].[PAIS] ([CODIGO])
);

