CREATE PROCEDURE [dbo].[spGetAllRematriculasPorDataRematricula]
	@dataInicial datetime,
	@dataFinal datetime
AS
BEGIN
SELECT
	REMATRICULA.CODIGO RematriculaId,
	REMATRICULA.COD_ENSINO_ALUNO MatriculaId,
	ENSINO_ALUNO.N_MAT AlunoId,
	ENSINO_ALUNO.COD_ENSINO CursoId,
	ENSINO.NOME_ENSINO CursoNome,
	REMATRICULA.DT_REMATRICULA DataRematricula,
	CONVERT(VARCHAR(30), REMATRICULA.DT_REMATRICULA, 103) DataRematriculaFormatado
FROM 
	REMATRICULA
JOIN 
	ENSINO_ALUNO ON REMATRICULA.COD_ENSINO_ALUNO = ENSINO_ALUNO.CODIGO
JOIN 
	ENSINO ON ENSINO_ALUNO.COD_ENSINO = ENSINO.CODIGO
WHERE
	DT_REMATRICULA between @dataInicial and @dataFinal
END