CREATE PROC [dbo].[usp_HISTORICO_ESCOLARInsert] 
    @COD_ENSINO_ALUNO int,
    @OBS varchar(MAX) = NULL,
    @COD_USUARIO_DIRETOR smallint,
    @COD_USUARIO_SECRETARIO smallint,
    @COD_USUARIO smallint,
    @DT_LIVRO date = NULL,
    @LIVRO varchar(MAX) = NULL,
    @PAGINA varchar(MAX) = NULL,
    @TERMO varchar(MAX) = NULL,
    @DT_DOCUMENTO date = NULL,
    @DT_CONCLUSAO date = NULL,
    @SERIE_ANTERIOR varchar(MAX) = NULL,
    @INSTITUICAO_ANTERIOR varchar(MAX) = NULL,
    @ANO_ANTERIOR int = NULL,
    @COD_CIDADE_ANTERIOR smallint = NULL,
    @FUNDAMENTACAO varchar(MAX) = NULL,
    @GDAE varchar(MAX) = NULL,
	@SEGUNDA_VIA BIT = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[HISTORICO_ESCOLAR] ([COD_ENSINO_ALUNO], [OBS], [COD_USUARIO_DIRETOR], [COD_USUARIO_SECRETARIO], [COD_USUARIO], [DT_LIVRO], [LIVRO], [PAGINA], [TERMO], [DT_DOCUMENTO], [DT_CONCLUSAO], [SERIE_ANTERIOR], [INSTITUICAO_ANTERIOR], [ANO_ANTERIOR], [COD_CIDADE_ANTERIOR], [FUNDAMENTACAO], [GDAE], [SEGUNDA_VIA])
	SELECT @COD_ENSINO_ALUNO, @OBS, @COD_USUARIO_DIRETOR, @COD_USUARIO_SECRETARIO, @COD_USUARIO, @DT_LIVRO, @LIVRO, @PAGINA, @TERMO, @DT_DOCUMENTO, @DT_CONCLUSAO, @SERIE_ANTERIOR, @INSTITUICAO_ANTERIOR, @ANO_ANTERIOR, @COD_CIDADE_ANTERIOR, @FUNDAMENTACAO, @GDAE, @SEGUNDA_VIA
	
	-- Begin Return Select <- do not remove
	SELECT [COD_ENSINO_ALUNO], [OBS], [COD_USUARIO_DIRETOR], [COD_USUARIO_SECRETARIO], [COD_USUARIO], [DT_LIVRO], [LIVRO], [PAGINA], [TERMO], [DT_DOCUMENTO], [DT_CONCLUSAO], [SERIE_ANTERIOR], [INSTITUICAO_ANTERIOR], [ANO_ANTERIOR], [COD_CIDADE_ANTERIOR], [FUNDAMENTACAO], [GDAE], [SEGUNDA_VIA]
	FROM   [dbo].[HISTORICO_ESCOLAR]
	WHERE  [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO
	-- End Return Select <- do not remove
               
	COMMIT
