CREATE PROC [dbo].[usp_DISCIPLINASelect] 
    @CODIGO tinyint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [CODIGO], [NOME], [NOME_HISTORICO], [HORARIO], [CAPACIDADE], [ORDEM], [BLOQ_ATRIBUICAO] 
	FROM   [dbo].[DISCIPLINA] 
	WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 

	COMMIT
