CREATE PROC [dbo].[usp_DEFICIENCIASelect] 
    @CODIGO smallint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [CODIGO], [NOME], [TIPO_DEFICIENCIA] 
	FROM   [dbo].[DEFICIENCIA] 
	WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 

	COMMIT
