CREATE PROC [dbo].[usp_MEDIAInsert] 
	@INSTITUICAO varchar(80),
	@COD_CIDADE INT,
    @COD_DISCIPLINA_ALUNO int,
    @VALOR varchar(20),
    @DT_MEDIA date,
    @COD_USUARIO smallint,
    @COD_USUARIO_MODIFICACAO smallint = NULL,
    @DT_MODIFICACAO datetime = NULL,
    @COD_ATENDIMENTO_ALUNO int = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[MEDIA] ([INSTITUICAO], [COD_CIDADE], [COD_DISCIPLINA_ALUNO], [VALOR], [DT_MEDIA], [COD_USUARIO], [COD_USUARIO_MODIFICACAO], [DT_MODIFICACAO], [COD_ATENDIMENTO_ALUNO])
	SELECT @INSTITUICAO, @COD_CIDADE, @COD_DISCIPLINA_ALUNO, @VALOR, @DT_MEDIA, @COD_USUARIO, @COD_USUARIO_MODIFICACAO, @DT_MODIFICACAO, @COD_ATENDIMENTO_ALUNO
	
	-- Begin Return Select <- do not remove
	SELECT [INSTITUICAO], [COD_CIDADE], [COD_DISCIPLINA_ALUNO], [VALOR], [DT_MEDIA], [COD_USUARIO], [COD_USUARIO_MODIFICACAO], [DT_MODIFICACAO], [COD_ATENDIMENTO_ALUNO]
	FROM   [dbo].[MEDIA]
	-- End Return Select <- do not remove
               
	COMMIT
