CREATE PROC [dbo].[usp_NOTADelete] 
    @COD_ATENDIMENTO_ALUNO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[NOTA]
	WHERE  [COD_ATENDIMENTO_ALUNO] = @COD_ATENDIMENTO_ALUNO

	COMMIT
