CREATE PROC [dbo].[usp_AREA_PROFESSORSelect] 
    @COD_PROFESSOR smallint,
    @COD_AREA tinyint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [COD_PROFESSOR], [COD_AREA] 
	FROM   [dbo].[AREA_PROFESSOR] 
	WHERE  ([COD_PROFESSOR] = @COD_PROFESSOR OR @COD_PROFESSOR IS NULL) 
	       AND ([COD_AREA] = @COD_AREA OR @COD_AREA IS NULL) 

	COMMIT
