CREATE PROC [dbo].[usp_NOTASelect] 
    @COD_ATENDIMENTO_ALUNO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [COD_ATENDIMENTO_ALUNO], [NOTA] 
	FROM   [dbo].[NOTA] 
	WHERE  ([COD_ATENDIMENTO_ALUNO] = @COD_ATENDIMENTO_ALUNO OR @COD_ATENDIMENTO_ALUNO IS NULL) 

	COMMIT
