CREATE PROC [dbo].[usp_PROFESSORSelect] 
    @CODIGO smallint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [CODIGO], [COD_DISCIPLINA], AREA_PROFESSOR.COD_AREA
	FROM   [dbo].[PROFESSOR]
	left JOIN AREA_PROFESSOR
	ON PROFESSOR.CODIGO = AREA_PROFESSOR.COD_PROFESSOR
	WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 

	COMMIT