CREATE PROC [dbo].[usp_MEDIASelect] 
    @COD_DISCIPLINA_ALUNO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [COD_DISCIPLINA_ALUNO], [INSTITUICAO], [COD_CIDADE], [VALOR], [DT_MEDIA], [COD_USUARIO], [COD_USUARIO_MODIFICACAO], [DT_MODIFICACAO], [COD_ATENDIMENTO_ALUNO] 
	FROM   [dbo].[MEDIA] 
	WHERE  ([COD_DISCIPLINA_ALUNO] = @COD_DISCIPLINA_ALUNO OR @COD_DISCIPLINA_ALUNO IS NULL) 

	COMMIT
