CREATE PROC [dbo].[usp_INATIVACAO_ALUNOSelect] 
    @CODIGO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [CODIGO], [COD_INATIVACAO], [COD_ENSINO_ALUNO], [COD_USUARIO], [DT_INATIVACAO], [MOTIVO] 
	FROM   [dbo].[INATIVACAO_ALUNO] 
	WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 

	COMMIT
