CREATE PROC [dbo].[usp_DISCIPLINA_ALUNOSelectOrdenadoPeloUltimoAtendimento] 
    @CODIGO int,
	@COD_ENSINO_ALUNO INT
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @CODIGO IS NOT NULL
		select DISCIPLINA_ALUNO.CODIGO, COD_ENSINO_ALUNO, COD_DISCIPLINA, ATUAL, CONCLUIDA, DT_ATENDIMENTO AS ULTIMO  from DISCIPLINA_ALUNO LEFT join (
		select COD_DISCIPLINA_ALUNO, MAX(DT_ATENDIMENTO) AS DT_ATENDIMENTO from ATENDIMENTO_ALUNO GROUP BY COD_DISCIPLINA_ALUNO) TB2
		on DISCIPLINA_ALUNO.CODIGO = TB2.COD_DISCIPLINA_ALUNO 
		--SELECT [CODIGO], [COD_ENSINO_ALUNO], [COD_DISCIPLINA], [ATUAL], [CONCLUIDA] 
		--FROM   [dbo].[DISCIPLINA_ALUNO] 
		WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 
		order by DT_ATENDIMENTO desc
	ELSE
		select DISCIPLINA_ALUNO.CODIGO, COD_ENSINO_ALUNO, COD_DISCIPLINA, ATUAL, CONCLUIDA, DT_ATENDIMENTO AS ULTIMO  from DISCIPLINA_ALUNO LEFT join (
		select COD_DISCIPLINA_ALUNO, MAX(DT_ATENDIMENTO) AS DT_ATENDIMENTO from ATENDIMENTO_ALUNO GROUP BY COD_DISCIPLINA_ALUNO) TB2
		on DISCIPLINA_ALUNO.CODIGO = TB2.COD_DISCIPLINA_ALUNO 
		--SELECT [CODIGO], [COD_ENSINO_ALUNO], [COD_DISCIPLINA], [ATUAL], [CONCLUIDA] 
		--FROM   [dbo].[DISCIPLINA_ALUNO] 
		WHERE  ([COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO OR @COD_ENSINO_ALUNO IS NULL)
		order by DT_ATENDIMENTO desc
	COMMIT