CREATE PROC [dbo].[usp_HISTORICO_ESCOLARDelete] 
    @COD_ENSINO_ALUNO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[HISTORICO_ESCOLAR]
	WHERE  [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO

	COMMIT
