CREATE PROC [dbo].[usp_LOG_CATRACASelect] 
    @CODIGO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [CODIGO], [COD_CARTAO_ACESSO], [DATA_HORA] 
	FROM   [dbo].[LOG_CATRACA] 
	WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 

	COMMIT
