CREATE PROC [dbo].[usp_INATIVACAO_ALUNOInsert] 
    @COD_INATIVACAO tinyint,
    @COD_ENSINO_ALUNO int = NULL,
    @COD_USUARIO smallint,
    @DT_INATIVACAO datetime,
    @MOTIVO varchar(MAX) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[INATIVACAO_ALUNO] ([COD_INATIVACAO], [COD_ENSINO_ALUNO], [COD_USUARIO], [DT_INATIVACAO], [MOTIVO])
	SELECT @COD_INATIVACAO, @COD_ENSINO_ALUNO, @COD_USUARIO, @DT_INATIVACAO, @MOTIVO
	
	-- Begin Return Select <- do not remove
	SELECT [CODIGO], [COD_INATIVACAO], [COD_ENSINO_ALUNO], [COD_USUARIO], [DT_INATIVACAO], [MOTIVO]
	FROM   [dbo].[INATIVACAO_ALUNO]
	WHERE  [CODIGO] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
