CREATE PROC [dbo].[usp_REMATRICULASelect] 
    @CODIGO int,
	@COD_ENSINO_ALUNO VARCHAR(MAX)
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @CODIGO IS NOT NULL
	SELECT [CODIGO], [DT_REMATRICULA], [COD_USUARIO], [COD_ENSINO_ALUNO] 
	FROM   [dbo].[REMATRICULA] 
	WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL)
	ELSE
	SELECT [CODIGO], [DT_REMATRICULA], [COD_USUARIO], [COD_ENSINO_ALUNO] 
	FROM   [dbo].[REMATRICULA] 
	WHERE  ([COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO OR @COD_ENSINO_ALUNO IS NULL)

	COMMIT
