CREATE PROC [dbo].[usp_HISTORICO_ESCOLARSelect] 
    @COD_ENSINO_ALUNO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [COD_ENSINO_ALUNO], [OBS], [COD_USUARIO_DIRETOR], [COD_USUARIO_SECRETARIO], [COD_USUARIO], [DT_LIVRO], [LIVRO], [PAGINA], [TERMO], [DT_DOCUMENTO], [DT_CONCLUSAO], [SERIE_ANTERIOR], [INSTITUICAO_ANTERIOR], [ANO_ANTERIOR], [COD_CIDADE_ANTERIOR], [FUNDAMENTACAO], [GDAE], [SEGUNDA_VIA]
	FROM   [dbo].[HISTORICO_ESCOLAR] 
	WHERE  ([COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO OR @COD_ENSINO_ALUNO IS NULL) 

	COMMIT
