CREATE PROC [dbo].[usp_INATIVACAO_ALUNOUpdate] 
    @CODIGO int,
    @COD_INATIVACAO tinyint,
    @COD_ENSINO_ALUNO int = NULL,
    @COD_USUARIO smallint,
    @DT_INATIVACAO datetime,
    @MOTIVO varchar(MAX) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[INATIVACAO_ALUNO]
	SET    [COD_INATIVACAO] = @COD_INATIVACAO, [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO, [COD_USUARIO] = @COD_USUARIO, [DT_INATIVACAO] = @DT_INATIVACAO, [MOTIVO] = @MOTIVO
	WHERE  [CODIGO] = @CODIGO
	
	-- Begin Return Select <- do not remove
	SELECT [CODIGO], [COD_INATIVACAO], [COD_ENSINO_ALUNO], [COD_USUARIO], [DT_INATIVACAO], [MOTIVO]
	FROM   [dbo].[INATIVACAO_ALUNO]
	WHERE  [CODIGO] = @CODIGO	
	-- End Return Select <- do not remove

	COMMIT
