CREATE PROC [dbo].[usp_CIDADESelect] 
    @CODIGO smallint,
	@COD_UF SMALLINT
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @CODIGO IS NOT NULL
		SELECT [CODIGO], [NOME], [COD_UF] 
		FROM   [dbo].[CIDADE] 
		WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL)
		ORDER BY NOME 
	ELSE
		SELECT [CODIGO], [NOME], [COD_UF] 
		FROM   [dbo].[CIDADE] 
		WHERE  ([COD_UF] = @COD_UF OR @COD_UF IS NULL) 
		ORDER BY NOME
	COMMIT
