CREATE PROC [dbo].[usp_ALUNOSelect] 
    @N_MAT int,
	@RG VARCHAR(MAX)
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @RG IS NULL 
	SELECT [N_MAT], [DT_MAT], [CPF], [RA], [RG], [UF_RG], [ORGAO_RG], [DT_RG], [NOME], [DT_NASCIMENTO], [SEXO], [NOME_MAE], [NOME_PAI], [ESTADO_CIVIL], [COR_ORIGEM_ETNICA], [TELEFONE], [CELULAR], [TERMO_MAT], [E_MAIL], [ATIVO], [CONCLUINTE], [OBS_PASSAPORTE], [APRESENTOU_CERTIDAO], [APRESENTOU_HISTORICO], [NOME_SOCIAL], [COD_USUARIO] 
	FROM   [dbo].[ALUNO] 
	WHERE  ([N_MAT] = @N_MAT OR @N_MAT IS NULL) 
	ELSE
	SELECT [N_MAT], [DT_MAT], [CPF], [RA], [RG], [UF_RG], [ORGAO_RG], [DT_RG], [NOME], [DT_NASCIMENTO], [SEXO], [NOME_MAE], [NOME_PAI], [ESTADO_CIVIL], [COR_ORIGEM_ETNICA], [TELEFONE], [CELULAR], [TERMO_MAT], [E_MAIL], [ATIVO], [CONCLUINTE], [OBS_PASSAPORTE], [APRESENTOU_CERTIDAO], [APRESENTOU_HISTORICO], [NOME_SOCIAL], [COD_USUARIO] 
	FROM   [dbo].[ALUNO] 
	WHERE  ([RG] = @RG OR @RG IS NULL) 
	COMMIT
