CREATE PROC [dbo].[usp_ATENDIMENTO_ALUNOSelect] 
    @CODIGO int,
	@COD_DISCIPLINA_ALUNO INT
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @CODIGO IS NOT NULL
		SELECT [CODIGO], [COD_DISCIPLINA_ALUNO], [COD_ATENDIMENTO], [COD_PROFESSOR], [DT_ATENDIMENTO], [COD_PROFESSOR_MODIFICACAO], [DT_MODIFICACAO], [MODULO], [ORDEM] 
		FROM   [dbo].[ATENDIMENTO_ALUNO] 
		WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 
		ORDER BY ORDEM
	ELSE
		SELECT [CODIGO], [COD_DISCIPLINA_ALUNO], [COD_ATENDIMENTO], [COD_PROFESSOR], [DT_ATENDIMENTO], [COD_PROFESSOR_MODIFICACAO], [DT_MODIFICACAO], [MODULO] , [ORDEM]
		FROM   [dbo].[ATENDIMENTO_ALUNO] 
		WHERE  ([COD_DISCIPLINA_ALUNO] = @COD_DISCIPLINA_ALUNO OR @COD_DISCIPLINA_ALUNO IS NULL) 
		ORDER BY ORDEM
	COMMIT
