CREATE PROC [dbo].[usp_ATIVIDADE_EXTRADelete] 
    @COD_ENSINO_ALUNO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[ATIVIDADE_EXTRA]
	WHERE  [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO

	COMMIT
