CREATE PROC [dbo].[usp_UFSelect] 
    @CODIGO smallint,
	@COD_PAIS smallint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @CODIGO IS NOT NULL
		SELECT [CODIGO], [NOME], [SIGLA], [COD_PAIS] 
		FROM   [dbo].[UF] 
		WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL)
		ORDER BY NOME
	ELSE
	SELECT [CODIGO], [NOME], [SIGLA], [COD_PAIS] 
		FROM   [dbo].[UF] 
		WHERE  (COD_PAIS = @COD_PAIS OR @COD_PAIS IS NULL)
		ORDER BY NOME
	COMMIT
