CREATE PROC [dbo].[usp_ENSINO_ALUNOSelect] 
    @CODIGO int,
	@N_MAT INT
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN
	IF @N_MAT IS NULL
		SELECT [CODIGO], [N_MAT], [COD_ENSINO], [ATUAL], [DT_INICIO], [DT_TERMINO] 
		FROM   [dbo].[ENSINO_ALUNO] 
		WHERE  ([CODIGO] = @CODIGO OR @CODIGO IS NULL) 
	ELSE
		SELECT [CODIGO], [N_MAT], [COD_ENSINO], [ATUAL], [DT_INICIO], [DT_TERMINO] 
		FROM   [dbo].[ENSINO_ALUNO] 
		WHERE  ([N_MAT] = @N_MAT OR @N_MAT IS NULL)
	COMMIT
