CREATE PROC [dbo].[usp_ATIVIDADE_EXTRAUpdate] 
    @COD_ENSINO_ALUNO int,
    @COD_USUARIO smallint,
    @DT_ATIVIDADE_EXTRA datetime
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[ATIVIDADE_EXTRA]
	SET    [COD_USUARIO] = @COD_USUARIO, [DT_ATIVIDADE_EXTRA] = @DT_ATIVIDADE_EXTRA
	WHERE  [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO
	
	-- Begin Return Select <- do not remove
	SELECT [COD_ENSINO_ALUNO], [COD_USUARIO], [DT_ATIVIDADE_EXTRA]
	FROM   [dbo].[ATIVIDADE_EXTRA]
	WHERE  [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO	
	-- End Return Select <- do not remove

	COMMIT
