CREATE PROC [dbo].[usp_ENDERECO_ALUNOSelect] 
    @N_MAT int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [N_MAT], [COD_CIDADE], [CEP], [LOGRADOURO], [NUMERO], [BAIRRO], [COMPLEMENTO] 
	FROM   [dbo].[ENDERECO_ALUNO] 
	WHERE  ([N_MAT] = @N_MAT OR @N_MAT IS NULL) 

	COMMIT
