CREATE PROC [dbo].[usp_DISCIPLINA_ALUNOUpdate] 
    @CODIGO int,
    @COD_ENSINO_ALUNO int = NULL,
    @COD_DISCIPLINA tinyint = NULL,
    @ATUAL bit = NULL,
    @CONCLUIDA bit = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[DISCIPLINA_ALUNO]
	SET    [COD_ENSINO_ALUNO] = @COD_ENSINO_ALUNO, [COD_DISCIPLINA] = @COD_DISCIPLINA, [ATUAL] = @ATUAL, [CONCLUIDA] = @CONCLUIDA
	WHERE  [CODIGO] = @CODIGO
	
	-- Begin Return Select <- do not remove
	SELECT [CODIGO], [COD_ENSINO_ALUNO], [COD_DISCIPLINA], [ATUAL], [CONCLUIDA]
	FROM   [dbo].[DISCIPLINA_ALUNO]
	WHERE  [CODIGO] = @CODIGO	
	-- End Return Select <- do not remove

	COMMIT
