
CREATE PROC [dbo].[usp_DEFICIENCIA_ALUNOSelect] 
    @N_MAT int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT N_MAT, COD_DEFICIENCIA, OBS 
	FROM   [dbo].[DEFICIENCIA_ALUNO] 
	WHERE  ([N_MAT] = @N_MAT OR @N_MAT IS NULL) 

	COMMIT
