CREATE PROC [dbo].[usp_AREA_PROFESSORDelete] 
    @COD_PROFESSOR smallint,
    @COD_AREA tinyint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[AREA_PROFESSOR]
	WHERE  [COD_PROFESSOR] = @COD_PROFESSOR
	       AND [COD_AREA] = @COD_AREA

	COMMIT
