CREATE PROC [dbo].[usp_ATENDIMENTO_ALUNODelete] 
    @CODIGO int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[ATENDIMENTO_ALUNO]
	WHERE  [CODIGO] = @CODIGO

	COMMIT
